### PR TITLE
Feat 178: Fix for provider tests to work with Maestro free tier key

### LINKED ISSUE #178: Make mashup provider tests compatible with Maestro's free tier key

### PR DESCRIPTION
**Pull request by sourabhxyz**
Current tests were hitting rate limit, this PR should fix for it.
Closes #178.

### CODE REVIEW

**Review by 4TT1L4 — APPROVED** [review]
LGTM.

File: tests/GeniusYield/Test/Providers/Mashup.hs [hunk 1]
```diff
@@ -75,18 +76,23 @@ providersMashupTests configs =
...
         let totalConfigs = length configs
         forM_ (zip [1 ..] configs) $ \(i, config) -> withCfgProviders config mempty $ \provider@GYProviders {..} -> do
+          threadDelay 1_000_000
           senderUTxOs <- runGYTxQueryMonadNode nid provider $ utxosAtAddress senderAddress
+          threadDelay 1_000_000
           let totalSenderFunds = foldMapUTxOs utxoValue senderUTxOs
               valueToSend     = totalSenderFunds `valueMinus` valueFromLovelace 5_000_000
               -- This way, UTxO distribution in test wallet should remain same.
           txBody <- runGYTxMonadNode nid provider [senderAddress] senderAddress Nothing $ pure $ mustHaveOutput $ mkGYTxOutNoDatum @'PlutusV2 senderAddress valueToSend
+          threadDelay 1_000_000
```
Comment (4TT1L4) [inline tests/GeniusYield/Test/Providers/Mashup.hs:95]: As just discussed, we should eventually refactor this, especially if the threadDelay is needed at even more places. For now this is fine, but we might want to do something about this in the future and not just copy this value to even more places.

For now this is OK, but we should not let the code quality degrade.
